### ISSUE TITLE
Rewards for social sharing/liking

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#187]
- [x] FB like (constant reward) #188 
- [x] Twitter follow (constant reward) #189 
- [x] FB Highscore share (one time reward) #190 
- [x] Twitter HS share (one time reward) #191
